# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joshua/TrackObj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joshua/TrackObj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joshua/TrackObj/CMakeFiles /home/joshua/TrackObj/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joshua/TrackObj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VFF_kinematics

# Build rule for target.
VFF_kinematics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VFF_kinematics
.PHONY : VFF_kinematics

# fast build rule for target.
VFF_kinematics/fast:
	$(MAKE) -f CMakeFiles/VFF_kinematics.dir/build.make CMakeFiles/VFF_kinematics.dir/build
.PHONY : VFF_kinematics/fast

#=============================================================================
# Target rules for targets named Optical_flow

# Build rule for target.
Optical_flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Optical_flow
.PHONY : Optical_flow

# fast build rule for target.
Optical_flow/fast:
	$(MAKE) -f CMakeFiles/Optical_flow.dir/build.make CMakeFiles/Optical_flow.dir/build
.PHONY : Optical_flow/fast

#=============================================================================
# Target rules for targets named KalmanFilter_trackingObj

# Build rule for target.
KalmanFilter_trackingObj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KalmanFilter_trackingObj
.PHONY : KalmanFilter_trackingObj

# fast build rule for target.
KalmanFilter_trackingObj/fast:
	$(MAKE) -f CMakeFiles/KalmanFilter_trackingObj.dir/build.make CMakeFiles/KalmanFilter_trackingObj.dir/build
.PHONY : KalmanFilter_trackingObj/fast

#=============================================================================
# Target rules for targets named test_kf

# Build rule for target.
test_kf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_kf
.PHONY : test_kf

# fast build rule for target.
test_kf/fast:
	$(MAKE) -f CMakeFiles/test_kf.dir/build.make CMakeFiles/test_kf.dir/build
.PHONY : test_kf/fast

#=============================================================================
# Target rules for targets named KFw_meanShift

# Build rule for target.
KFw_meanShift: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 KFw_meanShift
.PHONY : KFw_meanShift

# fast build rule for target.
KFw_meanShift/fast:
	$(MAKE) -f CMakeFiles/KFw_meanShift.dir/build.make CMakeFiles/KFw_meanShift.dir/build
.PHONY : KFw_meanShift/fast

KFw_meanShift.o: KFw_meanShift.cpp.o

.PHONY : KFw_meanShift.o

# target to build an object file
KFw_meanShift.cpp.o:
	$(MAKE) -f CMakeFiles/KFw_meanShift.dir/build.make CMakeFiles/KFw_meanShift.dir/KFw_meanShift.cpp.o
.PHONY : KFw_meanShift.cpp.o

KFw_meanShift.i: KFw_meanShift.cpp.i

.PHONY : KFw_meanShift.i

# target to preprocess a source file
KFw_meanShift.cpp.i:
	$(MAKE) -f CMakeFiles/KFw_meanShift.dir/build.make CMakeFiles/KFw_meanShift.dir/KFw_meanShift.cpp.i
.PHONY : KFw_meanShift.cpp.i

KFw_meanShift.s: KFw_meanShift.cpp.s

.PHONY : KFw_meanShift.s

# target to generate assembly for a file
KFw_meanShift.cpp.s:
	$(MAKE) -f CMakeFiles/KFw_meanShift.dir/build.make CMakeFiles/KFw_meanShift.dir/KFw_meanShift.cpp.s
.PHONY : KFw_meanShift.cpp.s

KalmanFilter_trackingObj.o: KalmanFilter_trackingObj.cpp.o

.PHONY : KalmanFilter_trackingObj.o

# target to build an object file
KalmanFilter_trackingObj.cpp.o:
	$(MAKE) -f CMakeFiles/KalmanFilter_trackingObj.dir/build.make CMakeFiles/KalmanFilter_trackingObj.dir/KalmanFilter_trackingObj.cpp.o
.PHONY : KalmanFilter_trackingObj.cpp.o

KalmanFilter_trackingObj.i: KalmanFilter_trackingObj.cpp.i

.PHONY : KalmanFilter_trackingObj.i

# target to preprocess a source file
KalmanFilter_trackingObj.cpp.i:
	$(MAKE) -f CMakeFiles/KalmanFilter_trackingObj.dir/build.make CMakeFiles/KalmanFilter_trackingObj.dir/KalmanFilter_trackingObj.cpp.i
.PHONY : KalmanFilter_trackingObj.cpp.i

KalmanFilter_trackingObj.s: KalmanFilter_trackingObj.cpp.s

.PHONY : KalmanFilter_trackingObj.s

# target to generate assembly for a file
KalmanFilter_trackingObj.cpp.s:
	$(MAKE) -f CMakeFiles/KalmanFilter_trackingObj.dir/build.make CMakeFiles/KalmanFilter_trackingObj.dir/KalmanFilter_trackingObj.cpp.s
.PHONY : KalmanFilter_trackingObj.cpp.s

Optical_flow.o: Optical_flow.cpp.o

.PHONY : Optical_flow.o

# target to build an object file
Optical_flow.cpp.o:
	$(MAKE) -f CMakeFiles/Optical_flow.dir/build.make CMakeFiles/Optical_flow.dir/Optical_flow.cpp.o
.PHONY : Optical_flow.cpp.o

Optical_flow.i: Optical_flow.cpp.i

.PHONY : Optical_flow.i

# target to preprocess a source file
Optical_flow.cpp.i:
	$(MAKE) -f CMakeFiles/Optical_flow.dir/build.make CMakeFiles/Optical_flow.dir/Optical_flow.cpp.i
.PHONY : Optical_flow.cpp.i

Optical_flow.s: Optical_flow.cpp.s

.PHONY : Optical_flow.s

# target to generate assembly for a file
Optical_flow.cpp.s:
	$(MAKE) -f CMakeFiles/Optical_flow.dir/build.make CMakeFiles/Optical_flow.dir/Optical_flow.cpp.s
.PHONY : Optical_flow.cpp.s

VFF_kinematics.o: VFF_kinematics.cpp.o

.PHONY : VFF_kinematics.o

# target to build an object file
VFF_kinematics.cpp.o:
	$(MAKE) -f CMakeFiles/VFF_kinematics.dir/build.make CMakeFiles/VFF_kinematics.dir/VFF_kinematics.cpp.o
.PHONY : VFF_kinematics.cpp.o

VFF_kinematics.i: VFF_kinematics.cpp.i

.PHONY : VFF_kinematics.i

# target to preprocess a source file
VFF_kinematics.cpp.i:
	$(MAKE) -f CMakeFiles/VFF_kinematics.dir/build.make CMakeFiles/VFF_kinematics.dir/VFF_kinematics.cpp.i
.PHONY : VFF_kinematics.cpp.i

VFF_kinematics.s: VFF_kinematics.cpp.s

.PHONY : VFF_kinematics.s

# target to generate assembly for a file
VFF_kinematics.cpp.s:
	$(MAKE) -f CMakeFiles/VFF_kinematics.dir/build.make CMakeFiles/VFF_kinematics.dir/VFF_kinematics.cpp.s
.PHONY : VFF_kinematics.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test_kf.dir/build.make CMakeFiles/test_kf.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test_kf.dir/build.make CMakeFiles/test_kf.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test_kf.dir/build.make CMakeFiles/test_kf.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... VFF_kinematics"
	@echo "... Optical_flow"
	@echo "... KalmanFilter_trackingObj"
	@echo "... test_kf"
	@echo "... KFw_meanShift"
	@echo "... KFw_meanShift.o"
	@echo "... KFw_meanShift.i"
	@echo "... KFw_meanShift.s"
	@echo "... KalmanFilter_trackingObj.o"
	@echo "... KalmanFilter_trackingObj.i"
	@echo "... KalmanFilter_trackingObj.s"
	@echo "... Optical_flow.o"
	@echo "... Optical_flow.i"
	@echo "... Optical_flow.s"
	@echo "... VFF_kinematics.o"
	@echo "... VFF_kinematics.i"
	@echo "... VFF_kinematics.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

